### PR TITLE
Enable copr builds and add packit config

### PR DESCRIPTION
**Pull request by dhodovsk**
Let us introduce [packit service](https://packit.dev) to you - the automation to integrate upstream open source projects into Fedora operating system.

After merging this PR, you are just a few steps away from RPM builds being automatically triggered on your PR's.
It means, that you'll be able to try and play with your change, packaged as an RPM.

But there is more. By using packit, you can for example enable adding new releases into Fedora Rawhide.

What are the next steps?
* Install [Packit-as-a-Service github application](https://github.com/marketplace/packit-as-a-service) in your repo
* In case you are first user, wait for account approval
* Enjoy the built RPMs!

For more info, please:
 * check out the documentation: https://packit.dev/docs/
 * contact @packit-service

### CODE REVIEW

**Comment by psss** [comment]
@dhodovsk, seems that I broken something ;-)

    Message: maximum recursion depth exceeded while calling a Python object

Could you have a look what wrong with the config? Thanks.

**Comment by TomasTomecek** [comment]
Playing with this locally and it works just fine.

Not sure if this project is cursed ( :D ) but you have hit 2 intermittent issues which are happening from time to time. Luckily, for the recursion thing, @csomh worked with the copr team and they came up with a solution which we are trying right now.

The other issue is that, somewhat, files are "lost" when packit performs operations on the git repo - in this case, the lost file is the whole .git dir. We suspect that volumes of our infra provided are tripping.

**Pull request merged**
