### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by atodorov**
I am still having some troubles with the XML-RPC Transport classes under Python 3, but the PR should take care of all differences between PY2 and PY3. Please review.

### CODE REVIEW

**Comment by lukaszachy** [comment]
Hello, I've only now find out about  this PR (thank you).
However `print(nitrate.TestPlan(1))` fails on `unicode` presence in `base.py` and later `utils.py`.

**Comment by zelial** [comment]
The u"..." can be safely converted to "...", can't they? Anyway, 2o3 suggests quite a lot more changes to be made for python3 compatibility...

**Comment by sharkcz** [comment]
For the record - lack of Python 3 support is causing removal from Fedora ...

**Comment by psss** [comment]
Migration to Python 3 has been completed by @ZelenyMartin in #10. @atodorov, thanks much for looking into this.

**Comment by sharkcz** [comment]
For the record, python-nitrate was dropped from Fedora > 31 on Oct 2nd, so additional steps will be required to get it back.

**Comment by psss** [comment]
Yes, python-nitrate has been successfully unretired:
https://pagure.io/releng/issue/8993

**Comment by sharkcz** [comment]
> Yes, python-nitrate has been successfully unretired:
> https://pagure.io/releng/issue/8993

thanks :-)

**Pull request closed without merging**
