### PR TITLE
Use psycopg(3) for Python 3.13 compatibility

### PR DESCRIPTION
**Pull request by martinhoyer**
Haven't done any testing yet, but at least it builds on F41 Python 3.13.  

Required by tmt[test-convert]

### CODE REVIEW

**Comment by martinhoyer** [comment]
looks like libpq is not being installed as a dependency of python3-psycopg3 package on certain distros.

**Comment by martinhoyer** [comment]
@lukaszachy Would you have a moment to check this, if you'll have rights to this repo?

**Review by lukaszachy — APPROVED** [review]
Thanks for fixing this

**Comment by martinhoyer** [comment]
@lukaszachy soo, I got lost in the specfile, so I've trimmed it a bit. Hoping epel8 will be fine now. wdyt? https://github.com/psss/python-nitrate/pull/49/commits/0938e7b0be753585e9195b13a49a7f55a0b5a6f6

**Comment by martinhoyer** [comment]
Also, I've noticed the tests were green, but it didn't look like they really ran. Let's see what happens with these changes

**Comment by martinhoyer** [comment]
I don't get it. Where does it tell it to require psycopg and not psycopg2 on epel8?
```
nothing provides python3.6dist(psycopg) needed by python3-nitrate-1.9.0-1.20240827144344806669.pr49.14.gdb1f011.el8.noarch
```
`%py3_build` `%py3_install`?

**Comment by lukaszachy** [comment]
I'm trying to understand what does `%python_enable_dependency_generator`. Which would be my guess...

**Comment by lukaszachy** [comment]
@martinhoyer The value comes from `setup.py` ( I tried to put 'foo' there and it appeared in require as  python3.6dist(foo)`)

**Comment by lukaszachy** [comment]
> looks like libpq is not being installed as a dependency of python3-psycopg3 package on certain distros.

Which distro was that?

**Comment by lukaszachy** [comment]
@martinhoyer I pushed commit to your PR, please check:
- use psycopg3 just for python3.13
- let setup.py be the source for requires (I've tried in mock epel8 and it works... we don't care about rhel-7 anymore, right?)
- remove the libpq explicit deps - f41 seems to have it fixed

**Comment by martinhoyer** [comment]
@lukaszachy @psss Looks green :)  

My only remaining point is "use psycopg2 on python<3.12" vs "use psycopg3 on python>3.13". The former make more sense to me - having it same on all current Fedoras, not just 41+... but no strong opinion.

**Comment by lukaszachy** [comment]
> My only remaining point is "use psycopg2 on python<3.12" vs "use psycopg3 on python>3.13". The former make more sense to me - having it same on all current Fedoras, not just 41+... but no strong opinion.

Personally I'd prefer to keep using psycopg2 where it is available and make psycopg3 to appear with python3.13+ becoming the base python. If only we would not need to fix libpq deps where python3-psycopg3 isn't packaged correctly :)

**Comment by martinhoyer** [comment]
> > My only remaining point is "use psycopg2 on python<3.12" vs "use psycopg3 on python>3.13". The former make more sense to me - having it same on all current Fedoras, not just 41+... but no strong opinion.
> 
> Personally I'd prefer to keep using psycopg2 where it is available and make psycopg3 to appear with python3.13+ becoming the base python. If only we would not need to fix libpq deps where python3-psycopg3 isn't packaged correctly :)

libpq is not being installed as a dep even with psycopg2 on el9 from what can tell

**Review by psss — APPROVED** [review]
Looks good, thanks!

**Comment by lukaszachy** [comment]
> libpq is not being installed as a dep even with psycopg2 on el9 from what can tell

Hm,.. I've just tested in VM and

```
Installing:
 python3-psycopg2                   x86_64                   2.8.6-6.el9                    rhel-AppStream                   192 k
Installing dependencies:
 libpq                              x86_64                   13.15-1.el9                    rhel-AppStream                   211 k
```

**Comment by martinhoyer** [comment]
> > libpq is not being installed as a dep even with psycopg2 on el9 from what can tell
> 
> Hm,.. I've just tested in VM and
> 
> ```
> Installing:
>  python3-psycopg2                   x86_64                   2.8.6-6.el9                    rhel-AppStream                   192 k
> Installing dependencies:
>  libpq                              x86_64                   13.15-1.el9                    rhel-AppStream                   211 k
> ```

hmm yeah, thanks for that correction. I must have confused myself with all the psycopgs everywhere.

**Pull request merged**
